spring:
  application:
    name: homework11
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics,prometheus,health